### ISSUE TITLE
Transfer over documentation from HTML to Markdown

### ISSUE THREAD

**Issue by vinlegend1** [fire-ui/fire-ui.github.io#7]
## Transfer from HTML to Markdown
- in `next-docs/src/posts`, we should (first delete something.md, woops) convert all the current documentation to markdown.
- Ex. accordion.html => accordion.md

## Structure of Markdown metadata
- In our markdowns, we have metadata:
- the following are required fields:
   - title: (name of component or page, this will show on the sidenav and in the `<title></title>`)
      - E.g. title: bro, title of page is `bro ~ Fire UI` and `"bro"` will be on sidenav
   - priority (priority is needed to sort files given priority... a higher number, a higher priority)
   - category (whether it's `"getting-started" | "layout" | "components"` describes under which category a page lies in the sidenav)
- the following are not required:
  - description (for specific description on a component for meta tags)
  - keywords (for specific keyword meta tags)

**Comment by vinlegend1** [comment]
forgot to mention that it's on the adding-next branch, let's not merge it for now until it's all converted :)

**Comment by kimlimjustin** [comment]
Okay! Ill convert it

**Comment by kimlimjustin** [comment]
I've convert them to markdown, and its work well. However, when I try to build static Html using `yarn build`, it shows me error on file `utils/FieUIJS.ts`, could you please fix this?
